# This workflow will do a clean install of node dependencies and check the code style

#  name: Linting and testing code CI

#  on:
#    push:
#      branches: [master]
#    pull_request:
#      branches: [master]

#  jobs:
#    build:
#      runs-on: ubuntu-latest
#      steps:
#        - uses: actions/checkout@v2
#        - name: Use Node.js 12.x
#          uses: actions/setup-node@v1
#          with:
#            node-version: 12.x
#        - run: npm ci
#        - run: npm run style
#        - run: npm run test


# name: Linting and testing code CI

# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]

# jobs:
#   build:
#     runs-on: windows-latest

#     steps:
#       - uses: actions/checkout@v2

#       - name: Use Node.js 18.x
#         uses: actions/setup-node@v3
#         with:
#           node-version: 18.x

#       - run: npm ci
#       - run: npm run style
#       - run: npm run test


name: Linting and testing code CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Update npm
        run: npm install -g npm@latest

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: npm ci
      - run: npm run style
      - run: npm run test
